services:
  mysql:
    image: mysql:latest
    container_name: loyalty_system
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loyalty_db
      MYSQL_USER: tnnh
      MYSQL_PASSWORD: 10012003
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
